development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: postgres
  password:
  host: localhost
  database: tint_data

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: postgres
  password:
  host: localhost
  database: tint_data_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: wicros
  password: wicros_tint
  host: tintdata.cfuavolkdrxj.ap-northeast-1.rds.amazonaws.com
  database: tint_data
